# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ai_service_pb2 as ai__service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ai_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AIServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SyncMessage = channel.unary_unary(
                '/proto.AIService/SyncMessage',
                request_serializer=ai__service__pb2.SyncRequest.SerializeToString,
                response_deserializer=ai__service__pb2.SyncResponse.FromString,
                _registered_method=True)
        self.ChatSummary = channel.unary_unary(
                '/proto.AIService/ChatSummary',
                request_serializer=ai__service__pb2.SummaryRequest.SerializeToString,
                response_deserializer=ai__service__pb2.SummaryResponse.FromString,
                _registered_method=True)
        self.SemanticSearch = channel.unary_unary(
                '/proto.AIService/SemanticSearch',
                request_serializer=ai__service__pb2.SearchRequest.SerializeToString,
                response_deserializer=ai__service__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.RevokeMessage = channel.unary_unary(
                '/proto.AIService/RevokeMessage',
                request_serializer=ai__service__pb2.RevokeRequest.SerializeToString,
                response_deserializer=ai__service__pb2.RevokeResponse.FromString,
                _registered_method=True)


class AIServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SyncMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChatSummary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SemanticSearch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RevokeMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AIServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SyncMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncMessage,
                    request_deserializer=ai__service__pb2.SyncRequest.FromString,
                    response_serializer=ai__service__pb2.SyncResponse.SerializeToString,
            ),
            'ChatSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.ChatSummary,
                    request_deserializer=ai__service__pb2.SummaryRequest.FromString,
                    response_serializer=ai__service__pb2.SummaryResponse.SerializeToString,
            ),
            'SemanticSearch': grpc.unary_unary_rpc_method_handler(
                    servicer.SemanticSearch,
                    request_deserializer=ai__service__pb2.SearchRequest.FromString,
                    response_serializer=ai__service__pb2.SearchResponse.SerializeToString,
            ),
            'RevokeMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.RevokeMessage,
                    request_deserializer=ai__service__pb2.RevokeRequest.FromString,
                    response_serializer=ai__service__pb2.RevokeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.AIService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('proto.AIService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AIService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SyncMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.AIService/SyncMessage',
            ai__service__pb2.SyncRequest.SerializeToString,
            ai__service__pb2.SyncResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ChatSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.AIService/ChatSummary',
            ai__service__pb2.SummaryRequest.SerializeToString,
            ai__service__pb2.SummaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SemanticSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.AIService/SemanticSearch',
            ai__service__pb2.SearchRequest.SerializeToString,
            ai__service__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RevokeMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.AIService/RevokeMessage',
            ai__service__pb2.RevokeRequest.SerializeToString,
            ai__service__pb2.RevokeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
